USE [master]
GO
/****** Object:  Database [HtmlCache]    Script Date: 07/12/2019 23:55:55 ******/
CREATE DATABASE [HtmlCache]
 CONTAINMENT = PARTIAL
 ON  PRIMARY 
( NAME = N'habitat.dev_Cache', FILENAME = N'D:\MSSQL13.MSSQLSERVER\MSSQL\DATA\habitat.dev_Cache.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'habitat.dev_Cache_log', FILENAME = N'D:\MSSQL13.MSSQLSERVER\MSSQL\Logs\habitat.dev_Cache_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [HtmlCache] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HtmlCache].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HtmlCache] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HtmlCache] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HtmlCache] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HtmlCache] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HtmlCache] SET ARITHABORT OFF 
GO
ALTER DATABASE [HtmlCache] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HtmlCache] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HtmlCache] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HtmlCache] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HtmlCache] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HtmlCache] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HtmlCache] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HtmlCache] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HtmlCache] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HtmlCache] SET  ENABLE_BROKER 
GO
ALTER DATABASE [HtmlCache] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HtmlCache] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HtmlCache] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HtmlCache] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HtmlCache] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HtmlCache] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HtmlCache] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HtmlCache] SET RECOVERY FULL 
GO
ALTER DATABASE [HtmlCache] SET  MULTI_USER 
GO
ALTER DATABASE [HtmlCache] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HtmlCache] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HtmlCache] SET DEFAULT_FULLTEXT_LANGUAGE = 1033 
GO
ALTER DATABASE [HtmlCache] SET DEFAULT_LANGUAGE = 1033 
GO
ALTER DATABASE [HtmlCache] SET NESTED_TRIGGERS = ON 
GO
ALTER DATABASE [HtmlCache] SET TRANSFORM_NOISE_WORDS = OFF 
GO
ALTER DATABASE [HtmlCache] SET TWO_DIGIT_YEAR_CUTOFF = 2049 
GO
ALTER DATABASE [HtmlCache] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HtmlCache] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HtmlCache] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'HtmlCache', N'ON'
GO
ALTER DATABASE [HtmlCache] SET QUERY_STORE = OFF
GO
USE [HtmlCache]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [HtmlCache]
GO
/****** Object:  User [htmlcacheuser]    Script Date: 07/12/2019 23:55:55 ******/
CREATE USER [htmlcacheuser] WITH PASSWORD=N'MfXSsqipDi8uWWNk7aaYA57JI/YhyNrD/zS51e+id0w=', DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [htmlcacheuser]
GO
/****** Object:  Table [dbo].[CacheItems]    Script Date: 07/12/2019 23:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CacheItems](
	[Id] [uniqueidentifier] NOT NULL,
	[ItemId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_CacheItems] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CacheKeys]    Script Date: 07/12/2019 23:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CacheKeys](
	[Id] [uniqueidentifier] NOT NULL,
	[SiteName] [varchar](250) NOT NULL,
	[SiteLang] [varchar](250) NOT NULL,
	[HtmlCacheKey] [varchar](500) NOT NULL,
	[HtmlCacheResult] [varchar](max) NOT NULL,
 CONSTRAINT [PK_CacheKeys] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CacheKeysItems]    Script Date: 07/12/2019 23:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CacheKeysItems](
	[Id] [uniqueidentifier] NOT NULL,
	[CacheKey_Id] [uniqueidentifier] NOT NULL,
	[CacheItem_Id] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_CacheKeysItems] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_CacheItems]    Script Date: 07/12/2019 23:55:55 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_CacheItems] ON [dbo].[CacheItems]
(
	[ItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = ON, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_CacheKeys]    Script Date: 07/12/2019 23:55:55 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_CacheKeys] ON [dbo].[CacheKeys]
(
	[HtmlCacheKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = ON, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_CacheKeysItems]    Script Date: 07/12/2019 23:55:55 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_CacheKeysItems] ON [dbo].[CacheKeysItems]
(
	[CacheKey_Id] ASC,
	[CacheItem_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = ON, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CacheKeysItems]  WITH CHECK ADD  CONSTRAINT [FK_CacheKeysItems_CacheItems] FOREIGN KEY([CacheItem_Id])
REFERENCES [dbo].[CacheItems] ([Id])
GO
ALTER TABLE [dbo].[CacheKeysItems] CHECK CONSTRAINT [FK_CacheKeysItems_CacheItems]
GO
ALTER TABLE [dbo].[CacheKeysItems]  WITH CHECK ADD  CONSTRAINT [FK_CacheKeysItems_CacheKeys] FOREIGN KEY([CacheKey_Id])
REFERENCES [dbo].[CacheKeys] ([Id])
GO
ALTER TABLE [dbo].[CacheKeysItems] CHECK CONSTRAINT [FK_CacheKeysItems_CacheKeys]
GO
USE [master]
GO
ALTER DATABASE [HtmlCache] SET  READ_WRITE 
GO
