// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace Foundation.HtmlCache.DB
{
    // CacheKeysTemp
    public class CacheKeysTemp
    {
        public Guid Id { get; set; } // Id (Primary key)
        public long CacheQueueId { get; set; } // CacheQueue_Id
        public Guid? CacheSiteLangId { get; set; } // CacheSiteLang_Id
        public string HtmlCacheKey { get; set; } // HtmlCacheKey (length: 500)
        public string HtmlCacheResult { get; set; } // HtmlCacheResult

        // Reverse navigation

        /// <summary>
        /// Child CacheItemsTemps where [CacheItemsTemp].[CacheKey_Id] point to this entity (FK_CacheItemsTemp_CacheKeysTemp)
        /// </summary>
        public virtual ICollection<CacheItemsTemp> CacheItemsTemps { get; set; } // CacheItemsTemp.FK_CacheItemsTemp_CacheKeysTemp

        /// <summary>
        /// Child CacheKeysItemsTemps where [CacheKeysItemsTemp].[CacheKey_Id] point to this entity (FK_CacheKeysItemsTemp_CacheKeysTemp)
        /// </summary>
        public virtual ICollection<CacheKeysItemsTemp> CacheKeysItemsTemps { get; set; } // CacheKeysItemsTemp.FK_CacheKeysItemsTemp_CacheKeysTemp

        // Foreign keys

        /// <summary>
        /// Parent CacheQueue pointed by [CacheKeysTemp].([CacheQueueId]) (FK_CacheKeysTemp_CacheQueue)
        /// </summary>
        public virtual CacheQueue CacheQueue { get; set; } // FK_CacheKeysTemp_CacheQueue

        /// <summary>
        /// Parent CacheSiteLangTemp pointed by [CacheKeysTemp].([CacheSiteLangId]) (FK_CacheKeysTemp_CacheSiteLangTemp)
        /// </summary>
        public virtual CacheSiteLangTemp CacheSiteLangTemp { get; set; } // FK_CacheKeysTemp_CacheSiteLangTemp

        public CacheKeysTemp()
        {
            CacheItemsTemps = new List<CacheItemsTemp>();
            CacheKeysItemsTemps = new List<CacheKeysItemsTemp>();
        }
    }

}
// </auto-generated>

