// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace Foundation.HtmlCache.DB
{
    // CacheKeyTemp
    [Table("CacheKeyTemp")]
    public class CacheKeyTemp
    {
        public Guid Id { get; set; } // Id (Primary key)
        public long CacheQueueId { get; set; } // CacheQueueId
        public Guid CacheSiteLangId { get; set; } // CacheSiteLangId
        public string HtmlCacheKey { get; set; } // HtmlCacheKey (length: 500)
        public string HtmlCacheResult { get; set; } // HtmlCacheResult

        // Reverse navigation

        /// <summary>
        /// Child CacheItemTemps where [CacheItemTemp].[CacheKeyId] point to this entity (FK_CacheItemTemp_CacheKeyTemp)
        /// </summary>
        public virtual ICollection<CacheItemTemp> CacheItemTemps { get; set; } // CacheItemTemp.FK_CacheItemTemp_CacheKeyTemp

        // Foreign keys

        /// <summary>
        /// Parent CacheQueue pointed by [CacheKeyTemp].([CacheQueueId]) (FK_CacheKeyTemp_CacheQueue)
        /// </summary>
        public virtual CacheQueue CacheQueue { get; set; } // FK_CacheKeyTemp_CacheQueue

        /// <summary>
        /// Parent CacheSiteLangTemp pointed by [CacheKeyTemp].([CacheSiteLangId]) (FK_CacheKeyTemp_CacheSiteLangTemp)
        /// </summary>
        public virtual CacheSiteLangTemp CacheSiteLangTemp { get; set; } // FK_CacheKeyTemp_CacheSiteLangTemp

        public CacheKeyTemp()
        {
            Id = Guid.NewGuid();
            CacheItemTemps = new List<CacheItemTemp>();
        }
    }

}
// </auto-generated>

