// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace Foundation.HtmlCache.DB
{
    // CacheKeysItems
    public class CacheKeysItem
    {
        public Guid Id { get; set; } // Id (Primary key)
        public Guid CacheKeyId { get; set; } // CacheKey_Id
        public Guid CacheItemId { get; set; } // CacheItem_Id

        // Foreign keys

        /// <summary>
        /// Parent CacheItem pointed by [CacheKeysItems].([CacheItemId]) (FK_CacheKeysItems_CacheItems)
        /// </summary>
        public virtual CacheItem CacheItem { get; set; } // FK_CacheKeysItems_CacheItems

        /// <summary>
        /// Parent CacheKey pointed by [CacheKeysItems].([CacheKeyId]) (FK_CacheKeysItems_CacheKeys)
        /// </summary>
        public virtual CacheKey CacheKey { get; set; } // FK_CacheKeysItems_CacheKeys
    }

}
// </auto-generated>

