// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace Foundation.HtmlCache.DB
{
    // CacheKeysItem
    [Table("CacheKeysItem")]
    public class CacheKeysItem
    {
        public Guid Id { get; set; } // Id (Primary key)
        public Guid CacheKeyId { get; set; } // CacheKeyId
        public Guid CacheItemId { get; set; } // CacheItemId

        // Foreign keys

        /// <summary>
        /// Parent CacheItem pointed by [CacheKeysItem].([CacheItemId]) (FK_CacheKeysItem_CacheItem)
        /// </summary>
        public virtual CacheItem CacheItem { get; set; } // FK_CacheKeysItem_CacheItem

        /// <summary>
        /// Parent CacheKey pointed by [CacheKeysItem].([CacheKeyId]) (FK_CacheKeysItem_CacheKey)
        /// </summary>
        public virtual CacheKey CacheKey { get; set; } // FK_CacheKeysItem_CacheKey

        public CacheKeysItem()
        {
            Id = Guid.NewGuid();
        }
    }

}
// </auto-generated>

