// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace Foundation.HtmlCache.DB
{
    // CacheItem
    [Table("CacheItem")]
    public class CacheItem
    {
        public Guid Id { get; set; } // Id (Primary key)
        public Guid ItemId { get; set; } // ItemId
        public Guid CacheKeyId { get; set; } // CacheKeyId

        // Reverse navigation

        /// <summary>
        /// Child CacheKeyItems where [CacheKeyItem].[CacheItemId] point to this entity (FK_CacheKeyItem_CacheItem)
        /// </summary>
        public virtual ICollection<CacheKeyItem> CacheKeyItems { get; set; } // CacheKeyItem.FK_CacheKeyItem_CacheItem

        // Foreign keys

        /// <summary>
        /// Parent CacheKey pointed by [CacheItem].([CacheKeyId]) (FK_CacheItem_CacheKey)
        /// </summary>
        public virtual CacheKey CacheKey { get; set; } // FK_CacheItem_CacheKey

        public CacheItem()
        {
            Id = Guid.NewGuid();
            CacheKeyItems = new List<CacheKeyItem>();
        }
    }

}
// </auto-generated>

