// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace Foundation.HtmlCache.DB
{
    // CacheSiteLangTemp
    public class CacheSiteLangTemp
    {
        public Guid Id { get; set; } // Id (Primary key)
        public long CacheQueueId { get; set; } // CacheQueue_Id
        public string Name { get; set; } // Name (length: 250)
        public string Lang { get; set; } // Lang (length: 250)

        // Reverse navigation

        /// <summary>
        /// Child CacheKeysTemps where [CacheKeysTemp].[CacheSiteLang_Id] point to this entity (FK_CacheKeysTemp_CacheSiteLangTemp)
        /// </summary>
        public virtual ICollection<CacheKeysTemp> CacheKeysTemps { get; set; } // CacheKeysTemp.FK_CacheKeysTemp_CacheSiteLangTemp

        // Foreign keys

        /// <summary>
        /// Parent CacheQueue pointed by [CacheSiteLangTemp].([CacheQueueId]) (FK_CacheSiteLangTemp_CacheQueue)
        /// </summary>
        public virtual CacheQueue CacheQueue { get; set; } // FK_CacheSiteLangTemp_CacheQueue

        public CacheSiteLangTemp()
        {
            CacheKeysTemps = new List<CacheKeysTemp>();
        }
    }

}
// </auto-generated>

