// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace Foundation.HtmlCache.DB
{
    // CacheHtmlTemp_CacheItemTemp
    [Table("CacheHtmlTemp_CacheItemTemp")]
    public partial class CacheHtmlTempCacheItemTemp
    {
        public Guid Id { get; set; } // Id (Primary key)
        public long CacheQueueId { get; set; } // CacheQueueId
        public Guid CacheHtmlTempId { get; set; } // CacheHtmlTempId
        public Guid CacheItemTempId { get; set; } // CacheItemTempId

        // Foreign keys

        /// <summary>
        /// Parent CacheHtmlTemp pointed by [CacheHtmlTemp_CacheItemTemp].([CacheHtmlTempId]) (FK_CacheHtmlTemp_CacheItemTemp_CacheHtmlTemp)
        /// </summary>
        public virtual CacheHtmlTemp CacheHtmlTemp { get; set; } // FK_CacheHtmlTemp_CacheItemTemp_CacheHtmlTemp

        /// <summary>
        /// Parent CacheItemTemp pointed by [CacheHtmlTemp_CacheItemTemp].([CacheItemTempId]) (FK_CacheHtmlTemp_CacheItemTemp_CacheItemTemp)
        /// </summary>
        public virtual CacheItemTemp CacheItemTemp { get; set; } // FK_CacheHtmlTemp_CacheItemTemp_CacheItemTemp

        /// <summary>
        /// Parent CacheQueue pointed by [CacheHtmlTemp_CacheItemTemp].([CacheQueueId]) (FK_CacheHtmlTemp_CacheItemTemp_CacheQueue)
        /// </summary>
        public virtual CacheQueue CacheQueue { get; set; } // FK_CacheHtmlTemp_CacheItemTemp_CacheQueue

        public CacheHtmlTempCacheItemTemp()
        {
            Id = Guid.NewGuid();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

