// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace Foundation.HtmlCache.DB
{
    // CacheHtmlTemp
    [Table("CacheHtmlTemp")]
    public partial class CacheHtmlTemp
    {
        public Guid Id { get; set; } // Id (Primary key)
        public long CacheQueueId { get; set; } // CacheQueueId
        public Guid CacheSiteTempId { get; set; } // CacheSiteTempId
        public string HtmlCacheKey { get; set; } // HtmlCacheKey (length: 5000)
        public string HtmlCacheResult { get; set; } // HtmlCacheResult
        public byte[] HtmlCacheKeyHash { get; set; } // HtmlCacheKeyHash (length: 64)

        // Reverse navigation

        /// <summary>
        /// Child CacheHtmlTempCacheItemTemps where [CacheHtmlTemp_CacheItemTemp].[CacheHtmlTempId] point to this entity (FK_CacheHtmlTemp_CacheItemTemp_CacheHtmlTemp)
        /// </summary>
        public virtual ICollection<CacheHtmlTempCacheItemTemp> CacheHtmlTempCacheItemTemps { get; set; } // CacheHtmlTemp_CacheItemTemp.FK_CacheHtmlTemp_CacheItemTemp_CacheHtmlTemp

        // Foreign keys

        /// <summary>
        /// Parent CacheQueue pointed by [CacheHtmlTemp].([CacheQueueId]) (FK_CacheHtmlTemp_CacheQueue)
        /// </summary>
        public virtual CacheQueue CacheQueue { get; set; } // FK_CacheHtmlTemp_CacheQueue

        /// <summary>
        /// Parent CacheSiteTemp pointed by [CacheHtmlTemp].([CacheSiteTempId]) (FK_CacheHtmlTemp_CacheSiteTemp)
        /// </summary>
        public virtual CacheSiteTemp CacheSiteTemp { get; set; } // FK_CacheHtmlTemp_CacheSiteTemp

        public CacheHtmlTemp()
        {
            Id = Guid.NewGuid();
            CacheHtmlTempCacheItemTemps = new List<CacheHtmlTempCacheItemTemp>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>

