// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace Foundation.HtmlCache.DB
{
    // CacheKey
    [Table("CacheKey")]
    public class CacheKey
    {
        public Guid Id { get; set; } // Id (Primary key)
        public Guid CacheSiteLangId { get; set; } // CacheSiteLangId
        public string HtmlCacheKey { get; set; } // HtmlCacheKey (length: 500)
        public string HtmlCacheResult { get; set; } // HtmlCacheResult

        // Reverse navigation

        /// <summary>
        /// Child CacheItems where [CacheItem].[CacheKeyId] point to this entity (FK_CacheItem_CacheKey)
        /// </summary>
        public virtual ICollection<CacheItem> CacheItems { get; set; } // CacheItem.FK_CacheItem_CacheKey

        /// <summary>
        /// Child CacheKeysItems where [CacheKeysItem].[CacheKeyId] point to this entity (FK_CacheKeysItem_CacheKey)
        /// </summary>
        public virtual ICollection<CacheKeysItem> CacheKeysItems { get; set; } // CacheKeysItem.FK_CacheKeysItem_CacheKey

        // Foreign keys

        /// <summary>
        /// Parent CacheSiteLang pointed by [CacheKey].([CacheSiteLangId]) (FK_CacheKey_CacheSiteLang)
        /// </summary>
        public virtual CacheSiteLang CacheSiteLang { get; set; } // FK_CacheKey_CacheSiteLang

        public CacheKey()
        {
            Id = Guid.NewGuid();
            CacheItems = new List<CacheItem>();
            CacheKeysItems = new List<CacheKeysItem>();
        }
    }

}
// </auto-generated>

