// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace Foundation.HtmlCache.DB
{
    // CacheItemTemp
    [Table("CacheItemTemp")]
    public class CacheItemTemp
    {
        public Guid Id { get; set; } // Id (Primary key)
        public long CacheQueueId { get; set; } // CacheQueueId
        public Guid ItemId { get; set; } // ItemId
        public Guid? CacheKeyId { get; set; } // CacheKeyId

        // Foreign keys

        /// <summary>
        /// Parent CacheKeyTemp pointed by [CacheItemTemp].([CacheKeyId]) (FK_CacheItemTemp_CacheKeyTemp)
        /// </summary>
        public virtual CacheKeyTemp CacheKeyTemp { get; set; } // FK_CacheItemTemp_CacheKeyTemp

        /// <summary>
        /// Parent CacheQueue pointed by [CacheItemTemp].([CacheQueueId]) (FK_CacheItemTemp_CacheQueue)
        /// </summary>
        public virtual CacheQueue CacheQueue { get; set; } // FK_CacheItemTemp_CacheQueue

        public CacheItemTemp()
        {
            Id = Guid.NewGuid();
        }
    }

}
// </auto-generated>

