// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace Foundation.HtmlCache.DB
{
    // CacheItemsTemp
    public class CacheItemsTemp
    {
        public Guid Id { get; set; } // Id (Primary key)
        public long? CacheQueueId { get; set; } // CacheQueue_Id
        public Guid ItemId { get; set; } // ItemId
        public Guid CacheKeyId { get; set; } // CacheKey_Id

        // Reverse navigation

        /// <summary>
        /// Child CacheKeysItemsTemps where [CacheKeysItemsTemp].[CacheItem_Id] point to this entity (FK_CacheKeysItemsTemp_CacheItemsTemp)
        /// </summary>
        public virtual ICollection<CacheKeysItemsTemp> CacheKeysItemsTemps { get; set; } // CacheKeysItemsTemp.FK_CacheKeysItemsTemp_CacheItemsTemp

        // Foreign keys

        /// <summary>
        /// Parent CacheKeysTemp pointed by [CacheItemsTemp].([CacheKeyId]) (FK_CacheItemsTemp_CacheKeysTemp)
        /// </summary>
        public virtual CacheKeysTemp CacheKeysTemp { get; set; } // FK_CacheItemsTemp_CacheKeysTemp

        /// <summary>
        /// Parent CacheQueue pointed by [CacheItemsTemp].([CacheQueueId]) (FK_CacheItemsTemp_CacheQueue)
        /// </summary>
        public virtual CacheQueue CacheQueue { get; set; } // FK_CacheItemsTemp_CacheQueue

        public CacheItemsTemp()
        {
            CacheKeysItemsTemps = new List<CacheKeysItemsTemp>();
        }
    }

}
// </auto-generated>

