// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Threading;
using System.Threading.Tasks;

namespace Foundation.HtmlCache.DB
{
    // CacheQueue
    public class CacheQueue
    {
        public long Id { get; set; } // Id (Primary key)
        public int CacheQueueMessageTypeId { get; set; } // CacheQueueMessageType_Id
        public bool Processing { get; set; } // Processing
        public byte[] UpdateVersion { get; set; } // UpdateVersion (length: 8)

        // Reverse navigation

        /// <summary>
        /// Child CacheItemsTemps where [CacheItemsTemp].[CacheQueue_Id] point to this entity (FK_CacheItemsTemp_CacheQueue)
        /// </summary>
        public virtual ICollection<CacheItemsTemp> CacheItemsTemps { get; set; } // CacheItemsTemp.FK_CacheItemsTemp_CacheQueue

        /// <summary>
        /// Child CacheKeysItemsTemps where [CacheKeysItemsTemp].[CacheQueue_Id] point to this entity (FK_CacheKeysItemsTemp_CacheQueue)
        /// </summary>
        public virtual ICollection<CacheKeysItemsTemp> CacheKeysItemsTemps { get; set; } // CacheKeysItemsTemp.FK_CacheKeysItemsTemp_CacheQueue

        /// <summary>
        /// Child CacheKeysTemps where [CacheKeysTemp].[CacheQueue_Id] point to this entity (FK_CacheKeysTemp_CacheQueue)
        /// </summary>
        public virtual ICollection<CacheKeysTemp> CacheKeysTemps { get; set; } // CacheKeysTemp.FK_CacheKeysTemp_CacheQueue

        /// <summary>
        /// Child CacheQueueBlockers where [CacheQueueBlocker].[CacheQueue_Id] point to this entity (FK_CacheQueueBlocker_CacheQueue)
        /// </summary>
        public virtual ICollection<CacheQueueBlocker> CacheQueueBlockers { get; set; } // CacheQueueBlocker.FK_CacheQueueBlocker_CacheQueue

        /// <summary>
        /// Child CacheSiteLangTemps where [CacheSiteLangTemp].[CacheQueue_Id] point to this entity (FK_CacheSiteLangTemp_CacheQueue)
        /// </summary>
        public virtual ICollection<CacheSiteLangTemp> CacheSiteLangTemps { get; set; } // CacheSiteLangTemp.FK_CacheSiteLangTemp_CacheQueue

        /// <summary>
        /// Child PublishedItems where [PublishedItems].[CacheQueue_Id] point to this entity (FK_PublishedItems_CacheQueue)
        /// </summary>
        public virtual ICollection<PublishedItem> PublishedItems { get; set; } // PublishedItems.FK_PublishedItems_CacheQueue

        // Foreign keys

        /// <summary>
        /// Parent CacheQueueMessageType pointed by [CacheQueue].([CacheQueueMessageTypeId]) (FK_CacheQueue_CacheQueueMessageType)
        /// </summary>
        public virtual CacheQueueMessageType CacheQueueMessageType { get; set; } // FK_CacheQueue_CacheQueueMessageType

        public CacheQueue()
        {
            CacheItemsTemps = new List<CacheItemsTemp>();
            CacheKeysItemsTemps = new List<CacheKeysItemsTemp>();
            CacheKeysTemps = new List<CacheKeysTemp>();
            CacheQueueBlockers = new List<CacheQueueBlocker>();
            CacheSiteLangTemps = new List<CacheSiteLangTemp>();
            PublishedItems = new List<PublishedItem>();
        }
    }

}
// </auto-generated>

