// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Validation;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Foundation.HtmlCache.DB
{
    public interface IItemTrackingProvider : IDisposable
    {
        DbSet<CacheHtml> CacheHtmls { get; set; } // CacheHtml
        DbSet<CacheHtmlCacheItem> CacheHtmlCacheItems { get; set; } // CacheHtml_CacheItem
        DbSet<CacheHtmlTemp> CacheHtmlTemps { get; set; } // CacheHtmlTemp
        DbSet<CacheItem> CacheItems { get; set; } // CacheItem
        DbSet<CacheItemTemp> CacheItemTemps { get; set; } // CacheItemTemp
        DbSet<CacheQueue> CacheQueues { get; set; } // CacheQueue
        DbSet<CacheQueueMessageType> CacheQueueMessageTypes { get; set; } // CacheQueueMessageType
        DbSet<CacheSite> CacheSites { get; set; } // CacheSite
        DbSet<CacheSiteTemp> CacheSiteTemps { get; set; } // CacheSiteTemp

        int SaveChanges();
        Task<int> SaveChangesAsync();
        Task<int> SaveChangesAsync(CancellationToken cancellationToken);
        DbChangeTracker ChangeTracker { get; }
        DbContextConfiguration Configuration { get; }
        Database Database { get; }
        DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        DbEntityEntry Entry(object entity);
        IEnumerable<DbEntityValidationResult> GetValidationErrors();
        DbSet Set(Type entityType);
        DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        // Stored Procedures
        int PurgeDatabase();
        // PurgeDatabaseAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

        List<UspGetCacheForSiteReturnModel> UspGetCacheForSite(string siteName);
        List<UspGetCacheForSiteReturnModel> UspGetCacheForSite(string siteName, out int procResult);
        Task<List<UspGetCacheForSiteReturnModel>> UspGetCacheForSiteAsync(string siteName);

        List<UspGetStatsReturnModel> UspGetStats();
        List<UspGetStatsReturnModel> UspGetStats(out int procResult);
        Task<List<UspGetStatsReturnModel>> UspGetStatsAsync();

        List<UspLockAndProcessCacheQueueEntryReturnModel> UspLockAndProcessCacheQueueEntry(string processingBy, out long? cacheQueueCount);
        List<UspLockAndProcessCacheQueueEntryReturnModel> UspLockAndProcessCacheQueueEntry(string processingBy, out long? cacheQueueCount, out int procResult);
        // UspLockAndProcessCacheQueueEntryAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

        int UspProcessCacheData(long? cacheQueueId);
        // UspProcessCacheDataAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

        int UspProcessDeleteHtmlFromCache(long? cacheQueueId, int? cacheQueueMessageTypeId);
        // UspProcessDeleteHtmlFromCacheAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

        int UspProcessDeleteSiteFromCache(long? cacheQueueId, int? cacheQueueMessageTypeId);
        // UspProcessDeleteSiteFromCacheAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

        int UspQueueCacheData(string siteName, string siteLang, string htmlCacheKey, string htmlCacheResult, DataTable ids);
        // UspQueueCacheDataAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

        int UspQueueDeleteSiteFromCache(string siteName, string siteLang);
        // UspQueueDeleteSiteFromCacheAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

        int UspQueuePublishData(string siteLang, DataTable ids);
        // UspQueuePublishDataAsync() cannot be created due to having out parameters, or is relying on the procedure result (int)

    }
}
// </auto-generated>

