// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.co.uk/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Registered to: Ashar Shah
// Company      : N/A
// Licence Type : Commercial
// Licences     : 1
// Valid until  : 11 DEC 2020
//
// Do not make changes directly to this file - edit the template instead.
// ------------------------------------------------------------------------------------------------

// <auto-generated>
// ReSharper disable CheckNamespace
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable NotAccessedVariable
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantCast
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// ReSharper disable UsePatternMatching

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;

namespace Foundation.HtmlCache.DB
{
    public class UspGetStatsReturnModel
    {
        public string TableName { get; set; }
        public string SchemaName { get; set; }
        public long? RowCounts { get; set; }
        public long? TotalSpaceKB { get; set; }
        public decimal? TotalSpaceMB { get; set; }
        public long? UsedSpaceKB { get; set; }
        public decimal? UsedSpaceMB { get; set; }
        public long? UnusedSpaceKB { get; set; }
        public decimal? UnusedSpaceMB { get; set; }
    }

}
// </auto-generated>

